<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Displays a table of all available/registered metrics.
 *
 * @package    tool_monitoring
 * @copyright  2025 MootDACH DevCamp
 *             Daniel Fainberg <d.fainberg@tu-berlin.de>
 *             Martin Gauk <martin.gauk@tu-berlin.de>
 *             Sebastian Rupp <sr@artcodix.com>
 *             Malte Schmitz <mal.schmitz@uni-luebeck.de>
 *             Melanie Treitinger <melanie.treitinger@ruhr-uni-bochum.de>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 *
 * {@noinspection PhpUnhandledExceptionInspection}
 */

use tool_monitoring\output\overview;

require_once(__DIR__ . '/../../../config.php');

global $PAGE, $OUTPUT;

require_login();

$context = context_system::instance();
require_capability('tool/monitoring:manage_metrics', $context);

// Handle parameters in links generated by Moodle tag system.
$tagcollid = optional_param('tc', -1, PARAM_INT);
$tagname = optional_param('tag', '', PARAM_TAG);
if ($tagname) {
    overview::redirect_tagname($tagcollid, $tagname);
}

// Handle tags parameter for filtering of multiple tags.
$taglist = optional_param('tags', '', PARAM_TAGLIST);
$params = [];
if ($taglist) {
    $tags = explode(',', $taglist);
    $params['tags'] = $taglist;
} else {
    $tags = [];
}

$PAGE->set_url('/admin/tool/monitoring/', $params);
$PAGE->set_context($context);
$PAGE->set_title(get_string('monitoring_metrics', 'tool_monitoring'));
$PAGE->set_heading(get_string('monitoring_metrics', 'tool_monitoring'));
$overview = new overview($tags);
echo $OUTPUT->header();
echo $OUTPUT->render($overview);
echo $OUTPUT->footer();
